### ISSUE TITLE
No named parameter with the name 'thickness'.

### ISSUE THREAD

**Issue by mzyon** [MayLau-CbL/flutter_horizontal_data_table#1]
Context: Found this candidate, but the arguments don't match.
  const Divider({
        ^

**Comment by MayLau-CbL** [comment]
@mzyon 
I have tried to run with the example test code and cannot repeat this issue.
Would you mind pasting your flutter doctor log and the way you call the HorizontalDataTable to see if I can simulate this?

**Comment by MayLau-CbL** [comment]
No further detail, if repeated will reopen
