### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SulaimanBosu** [MayLau-CbL/flutter_horizontal_data_table#103]
![1662105043257](https://user-images.githubusercontent.com/103396957/188086891-a2f30d27-363f-4357-8166-184830bacf23.jpg)
**Describe the bug**
Description of what the bug is.

**Platform**
Please describe the affected platfrom(eg. IOS, Android)

**Screen Captures or Debug Log**
PS D:\Project\item_history> flutter run
Launching lib\main.dart on SM J730GM in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01       
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01   
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:525:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:673:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:756:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:779:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:787:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/smart_refresher.dart:794:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/scroll/custom_scroll_bar.dart:24:9: Error: No named parameter with the name 'thumbVisibility'.
        thumbVisibility: this.scrollbarStyle?.isAlwaysShown ?? false,
        ^^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/scrollbar.dart:865:9: Context: Found this candidate, but the arguments don't match.
  const RawScrollbar({
        ^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/scroll/custom_scroll_bar.dart:35:7: Error: No named parameter with the name 'thumbVisibility'.
      thumbVisibility: this.scrollbarStyle?.isAlwaysShown ?? false,
      ^^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:261:33: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
        WidgetsBinding.instance.addPostFrameCallback((_) {
                                ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:291:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-3.7.0/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:394:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Running Gradle task 'assembleDebug'...                             26.9s
Exception: Gradle task assembleDebug failed with exit code 1
PS D:\Project\item_history>
 
**Additional context**

**Comment by MayLau-CbL** [comment]
This error should be 2 issues:
1. android project gradle, the new ns to old ns should be able to be solved by upgrading to the latest gradle version
2. after flutter 3.3 some of the null checker will cause error, please try with the latest package version

**Comment by MayLau-CbL** [comment]
no further comment, close this first
