### ISSUE TITLE
[Feature] Export to CSV

### ISSUE THREAD

**Issue by pryshrm** [MayLau-CbL/flutter_horizontal_data_table#104]
**Describe the Feature**
A small icon or button that will let the user download a csv file of the data displayed by the view.

**Describe the Solution**
Not really sure how to go about it.

**Comment by MayLau-CbL** [comment]
Take a try with the csv package, https://pub.dev/packages/csv

**Comment by MayLau-CbL** [comment]
As no further comment, will close this discussion for now.
