### ISSUE TITLE
[Bug] Serveral Errors with smart_refresher:  "SpringDescription" 

### ISSUE THREAD

**Issue by FloFerstl** [MayLau-CbL/flutter_horizontal_data_table#106]
Hey :)
after starting my app in flutter-debug-mode after a while, this error appears:

/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(828,9): error G5FE39F1E: Type 'SpringDescription' not found. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(946,5): error G5FE39F1E: Type 'SpringDescription' not found. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/internals/refresh_physics.dart(28,9): error G5FE39F1E: Type 'SpringDescription' not found. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(903,37): error GF7CA4DBF: Couldn't find constructor 'SpringDescription'. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(347,23): error GF7CA4DBF: Couldn't find constructor 'SpringDescription'. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(828,9): error G104F1F23: 'SpringDescription' isn't a type. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/smart_refresher.dart(946,5): error G104F1F23: 'SpringDescription' isn't a type. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.2+2/lib/refresh/pull_to_refresh/src/internals/refresh_physics.dart(28,9): error G104F1F23: 'SpringDescription' isn't a type. [D:\software\build\windows\flutter\flutter_assemble.vcxproj]

Do you know, how to handle this error?

**Comment by MayLau-CbL** [comment]
seems similar bug to #102 
Are you using flutter 3.3 or later?

**Comment by Dilshodbek007** [comment]
I also faced this error? i can't find any  solution.

**Comment by MayLau-CbL** [comment]
@Dilshodbek007 this usually appear when flutter version is >3.3. you can try to upgrade the flutter version or use the old package version.

**Comment by MayLau-CbL** [comment]
no further comment, close this first
