### ISSUE TITLE
[Question]Are there any problems with the keyboard scrolling to the top when it is activated?

### ISSUE THREAD

**Issue by nrikiji** [MayLau-CbL/flutter_horizontal_data_table#107]
Are there any problems with the keyboard scrolling to the top when it is activated?

```
HorizontalDataTable(
    // Expected behavior in previous versions
    // verticalScrollController: ref.read(appProvider.notifier).scrollController,

    // If I modify it this way, it scrolls to the top every time I open the keyboard
    onScrollControllerReady: (vertical, _) {
      ref.read(appProvider.notifier).scrollController = vertical;
    },
);
```

**Comment by MayLau-CbL** [comment]
Can you make a simple demo project to repeat this problem? I have tried with textfield and this widget, the scroll seems fine.
You can also try to set break point to check what is triggering the scroll.



https://user-images.githubusercontent.com/56990610/189590496-18edf80c-d24d-4348-b94c-9904200f507e.mov

**Comment by nrikiji** [comment]
Thank you for confirming.

Sorry, I'm not sure how to fix the problem. I tried it with a simple app and could not reproduce it. I will close this issue as there seems to be a problem with my implementation.

**Comment by nrikiji** [comment]
It seems that there was still a problem with my implementation. I leave you with the problematic code and the resolved code.
It seems that the problem was that the height of the leftSideChildren was not specified.

Bad 
```dart
HorizontalDataTable(
　・・・
  leftHandSideColumnWidth: 0.0,
  leftSideChildren: years.map((x) => Container()).toList(),
  rightSideChildren: years.map((x) => rightSideItemBuilder(context)).toList(),
};
```

Good
```dart
HorizontalDataTable(
　・・・
  leftHandSideColumnWidth: 0.0,
  leftSideChildren: years.map((x) => Container(height: HEIGHT)).toList(),
  rightSideChildren: years.map((x) => rightSideItemBuilder(context)).toList(),
};
```

I'm sorry for troubling you. Thank you.
