### ISSUE TITLE
iOS存在回弹效果，导致左右不同步

### ISSUE THREAD

**Issue by zhusongyu** [MayLau-CbL/flutter_horizontal_data_table#11]
![flutterdemo](https://user-images.githubusercontent.com/33612211/89155764-0f81ca00-d59c-11ea-9309-2e1992c46bc1.gif)

如图，在iOS上，因为存在回弹属性，当在顶部继续拖动的时候就会出现左右不同步现象，请问一下，这个bug好解吗？

**Comment by MayLau-CbL** [comment]
你好！其實這個問題沿於這裡的做法實際上是利用2個ListView Widget 再透過它們的scroll notification同步scrolling。在另一個PR有提出到加上pull refresh功能時，我發現這個同步, 我發覺難以一同同步它們的scroll physic，也就是看到的IOS 會有一邊先回彈的問題。暫時未有頭緒可以怎樣保持performance的同時去實行這個effect。我會繼續研究一下。

這是個人建議，若果時間不多的話，設計上又可以商量可以自統一用android 的scroll effect來回避問題，若然不行，如果data 的量不多，可以考慮使用一個vertical 的ListView Widget, 每一個child 都有一個horizontal的scroll child 加上scroll notification來實現。但注意一下，我預計在一些入門手機應該慢得很。

若大家有什麼建議可以做到這個效果也歡迎提議，謝謝！
