### ISSUE TITLE
[Bug]Use error reporting

### ISSUE THREAD

**Issue by tuke-code** [MayLau-CbL/flutter_horizontal_data_table#111]
**Describe the bug**
Use error reporting
**Platform**
Android
**Screen Captures or Debug Log**

`Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-000418DC0262801E }
{ platform:macOS, arch:x86_64, id:00006000-000418DC0262801E }
Invalid depfile: /Users/huangyuanfu/StudioProjects/smart_site/.dart_tool/flutter_build/270c70707a508c36f1b40532375dcbca/kernel_snapshot.d
Invalid depfile: /Users/huangyuanfu/StudioProjects/smart_site/.dart_tool/flutter_build/270c70707a508c36f1b40532375dcbca/kernel_snapshot.d
Error: Couldn't resolve the package 'scrollable_table_view' in 'package:scrollable_table_view/scrollable_table_view.dart'.
lib/pages/material_requisition.dart:4:8: Error: Not found: 'package:scrollable_table_view/scrollable_table_view.dart'
import 'package:scrollable_table_view/scrollable_table_view.dart';
       ^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/indicator/waterdrop_header.dart:159:46: Error: Property 'axisDirection' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
                      Scrollable.of(context).axisDirection == AxisDirection.up
                                             ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/indicator/waterdrop_header.dart:165:46: Error: Property 'axisDirection' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
                      Scrollable.of(context).axisDirection == AxisDirection.up
                                             ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/indicator/waterdrop_header.dart:169:46: Error: Property 'axisDirection' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
                      Scrollable.of(context).axisDirection == AxisDirection.up
                                             ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:335:42: Error: Property 'axisDirection' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
                  Scrollable.of(context).axisDirection == AxisDirection.up
                                         ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:390:43: Error: Property 'position' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
      if (mounted) Scrollable.of(context).position.correctBy(0.00001);
                                          ^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart:630:63: Error: Property 'position' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
    final ScrollPosition newPosition = Scrollable.of(context).position;
                                                              ^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/indicator/material_indicator.dart:74:45: Error: Property 'position' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
      if (mounted && Scrollable.of(context).position.pixels <= 0)
                                            ^^^^^^^^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/horizontal_data_table-4.1.4+1/lib/refresh/pull_to_refresh/src/internals/slivers.dart:182:30: Error: Property 'position' cannot be accessed on 'ScrollableState?' because it is potentially null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Try accessing using ?. instead.
      Scrollable.of(context).position.activity!.applyNewDimensions();
                             ^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Ascrollable_table_view%2Fscrollable_table_view.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>
#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>

Command PhaseScriptExecution failed with a nonzero exit code
/Users/huangyuanfu/StudioProjects/smart_site/macos/Runner.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'Flutter Assemble' from project 'Runner')
/Users/huangyuanfu/StudioProjects/smart_site/macos/Runner.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Exception: Build process failed
`
**Additional context**

**Comment by MayLau-CbL** [comment]
Hi @tuke-code, do you mind also showing the `flutter doctor -v` msg and the package version you have used?

**Comment by MayLau-CbL** [comment]
should be resolved along the 4.1.5 update.
detail please check the README.md's available package version table.
Close this issue for now
