### ISSUE TITLE
当 Scaffold 去掉 appBar 时，Header 上面有边距

### ISSUE THREAD

**Issue by Tang3210** [MayLau-CbL/flutter_horizontal_data_table#124]
当 Scaffold 去掉 appBar 时，Header 上面有边距，

**Comment by Tang3210** [comment]
安卓手机，示例：

**Comment by Tang3210** [comment]
安卓手机，示例：import 'package:flutter/material.dart';
import 'package:horizontal_data_table/horizontal_data_table.dart';

import 'data/user.dart';

class SimpleTableRefreshLoadPage extends StatefulWidget {
  const SimpleTableRefreshLoadPage({
    Key? key,
    required this.user,
  }) : super(key: key);
  final User user;

  @override
  State<SimpleTableRefreshLoadPage> createState() =>
      _SimpleTableRefreshLoadPageState();
}

class _SimpleTableRefreshLoadPageState
    extends State<SimpleTableRefreshLoadPage> {
  final HDTRefreshController _hdtRefreshController = HDTRefreshController();

  @override
  void initState() {
    widget.user.initData(100);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(title: const Text('Pull-to-refresh Table')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [

          Container(
            color: Colors.red,
            child: Text(
              'HorizontalDataTable',
            ),
          ),


          Expanded(child: Container(
            color: Colors.blue,
            child: HorizontalDataTable(
              leftHandSideColumnWidth: 100,
              rightHandSideColumnWidth: 600,
              isFixedHeader: true,
              headerWidgets: _getTitleWidget(),
              isFixedFooter: true,
              footerWidgets: _getTitleWidget(),
              leftSideItemBuilder: _generateFirstColumnRow,
              rightSideItemBuilder: _generateRightHandSideColumnRow,
              itemCount: 1,
              rowSeparatorWidget: const Divider(
                color: Colors.black38,
                height: 1.0,
                thickness: 0.0,
              ),
              leftHandSideColBackgroundColor: const Color(0xFFFFFFFF),
              rightHandSideColBackgroundColor: const Color(0xFFFFFFFF),
              itemExtent: 55,

              enablePullToRefresh: true,
              enablePullToLoadNewData: true,
              fixedSidePlaceHolderRefreshIndicator : const PlaceholderHeader(),
              fixedSidePlaceHolderLoadIndicator : const PlaceholderFooter(),
              refreshIndicator: const ClassicHeader(),
              loadIndicator: const ClassicFooter(),
              htdRefreshController: _hdtRefreshController,
              onRefresh: () async {
                await Future.delayed(Duration(seconds: 1));
                _hdtRefreshController.refreshCompleted();
              },
              onLoad: () {},
            ),))
        ],
      ),
    );
  }

  List<Widget> _getTitleWidget() {
    return [
      _getTitleItemWidget('Name', 100),
      _getTitleItemWidget('Status', 100),
      _getTitleItemWidget('Phone', 200),
      _getTitleItemWidget('Register', 100),
      _getTitleItemWidget('Termination', 200),
    ];
  }

  Widget _getTitleItemWidget(String label, double width) {
    return Container(
      width: width,
      height: 56,
      padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
      alignment: Alignment.centerLeft,
      child: Text(label, style: const TextStyle(fontWeight: FontWeight.bold)),
    );
  }

  Widget _generateFirstColumnRow(BuildContext context, int index) {
    return Container(
      width: 100,
      height: 52,
      padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
      alignment: Alignment.centerLeft,
      child: Text(widget.user.userInfo[index].name),
    );
  }

  Widget _generateRightHandSideColumnRow(BuildContext context, int index) {
    return Row(
      children: <Widget>[
        Container(
          width: 100,
          height: 52,
          padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
          child: Row(
            children: <Widget>[
              Icon(
                  widget.user.userInfo[index].status
                      ? Icons.notifications_off
                      : Icons.notifications_active,
                  color: widget.user.userInfo[index].status
                      ? Colors.red
                      : Colors.green),
              Text(widget.user.userInfo[index].status ? 'Disabled' : 'Active')
            ],
          ),
        ),
        Container(
          width: 200,
          height: 52,
          padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
          child: Text(widget.user.userInfo[index].phone),
        ),
        Container(
          width: 100,
          height: 52,
          padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
          child: Text(widget.user.userInfo[index].registerDate),
        ),
        Container(
          width: 200,
          height: 52,
          padding: const EdgeInsets.fromLTRB(5, 0, 0, 0),
          alignment: Alignment.centerLeft,
          child: Text(widget.user.userInfo[index].terminationDate),
        ),
      ],
    );
  }
}

**Comment by MayLau-CbL** [comment]
不好意思，放假了，覆得比較慢
我run不到你的sample code，但我自己手機sim看到如果remove Scaffold就不會有這個情況，看似是Scaffold 本身的設定原因。
如果你remove 了還是有這情況，可以給我你手機的型號，我找個方法看看

**Comment by Tang3210** [comment]
> 不好意思，放假了，覆得比較慢 我run不到你的sample code，但我自己手機sim看到如果remove Scaffold就不會有這個情況，看似是Scaffold 本身的設定原因。 如果你remove 了還是有這情況，可以給我你手機的型號，我找個方法看看

解决了，使用  MediaQuery.removePadding(removeTop: true)  包裹下就没问题了
