### ISSUE TITLE
I can't use HorizontalDataTable in listview single singlechildscrollview how to use please

### ISSUE THREAD

**Issue by pheeraphat-jun** [MayLau-CbL/flutter_horizontal_data_table#14]

**Comment by MayLau-CbL** [comment]
@pheeraphat-jun, do you mean sth like this?

_________________________
|    Listview                   |
|                                    |
|________________________|
|    Horizontal Table      |
|                                    |
|________________________|
|                                    |
|________________________||

**Comment by pheeraphat-jun** [comment]
yes

**Comment by MayLau-CbL** [comment]
You may take a look at this. Embedding inside listview or SingleChildScrollView should be similar. The most important thing is to limit the size of the horizontal data table widget.
[home_page.txt](https://github.com/MayLau-CbL/flutter_horizontal_data_table/files/5611670/home_page.txt)
