### ISSUE TITLE
加载更多与下拉加载，大量数据加载

### ISSUE THREAD

**Issue by jingzhanwu** [MayLau-CbL/flutter_horizontal_data_table#15]
支持下拉与加载更多的配置吗，另外如果列表有上千条上万条数据需要分页加载显示，性能会不会有影响

**Comment by MayLau-CbL** [comment]
因為目前的寫法，暫時仍未能配合常用的那些下拉的package，我見[簡書](https://www.jianshu.com/p/1cb890b4897b)好像有人做到類似的效果，你可以嘗試問問看看。這個我見前最多只試過約5000條的資料顯示，都是文字的data，我做了android的profile看過效能都是能接受的frame rate。

**Comment by MayLau-CbL** [comment]
Added new issue for this feature https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/16
