### ISSUE TITLE
Passing variable to dialog from table cell

### ISSUE THREAD

**Issue by Ivan-Law** [MayLau-CbL/flutter_horizontal_data_table#18]
I tried to pop up a dialog box from data table cell by user clicking, but unable to pass the cell content variable to 'onTap' or 'onPressed'. Neither success on both "_generateFirstColumnRow," or "_generateRightHandSideColumnRow".

Any advice? Thanks.

Ivan Law

**Comment by MayLau-CbL** [comment]
Hi, Ivan! I have received your email. I am sorry for the late reply. I hope the attached example can solve your problems. The attached example code is suggested a way on how to call the dialog and also displayed the value inside the onPressed function should updated along the scrolling. If there is any further questions, please feel free to ask.
[example.txt](https://github.com/MayLau-CbL/flutter_horizontal_data_table/files/5758664/main.txt)

**Comment by Ivan-Law** [comment]
Hi May, thanks for the update! I notice you embraced AlertDialog inside showDialog as 2 layers from your sample code, which inspired me to debug my code. Thanks a lot.
Happy coding 2021!
