### ISSUE TITLE
Scroll right when data changes

### ISSUE THREAD

**Issue by guavajellyaaron** [MayLau-CbL/flutter_horizontal_data_table#19]
I have a table that is dynamically generated with data. When new data is added it would be great if the table would automatically scroll to the right to display new data.

I was able to make this work locally by adding a function called `onRightHandSideColumnWidthChange` that passed in the `_rightHorizontalScrollController`. Then in the callback I added this code.

```javascript
onRightHandSideColumnWidthChange: (ScrollController _controller) {
            if (rightHandSideColumnWidth + leftHandSideColumnWidth >=
                containerWidth) {
              _controller.animateTo(_controller.position.maxScrollExtent + leftHandSideColumnWidth,
                  curve: Curves.easeOut,
                  duration: const Duration(milliseconds: 100));
            }
          }
```

This is a obviously a very specific use case but it might be good to expose `onRightHandSideColumnWidthChange`.  Thoughts?

**Comment by MayLau-CbL** [comment]
Hi, @guavajellyaaron! I have considered your suggestion. Would it be easier if I just expose the horizontal and vertical scroll controller that allowing use animateTo and other scroll feature?

**Comment by guavajellyaaron** [comment]
Yes. For now, that would be great!
