### ISSUE TITLE
Error when overscrolled to either right or top

### ISSUE THREAD

**Issue by dzluppin** [MayLau-CbL/flutter_horizontal_data_table#2]
This is caused by Material widget (lines: 131,158,182) not accepting elevation below 0 generated by private function _getElevation.

The solution for me is just to add .abs() function after calling _gelElevation.

**Comment by MayLau-CbL** [comment]
Thank you, @dzluppin ! I can simulate this issue now. I will commit a new version this weekend :-)

**Comment by MayLau-CbL** [comment]
dependence update and the above fix includes in the v1.0.1
