### ISSUE TITLE
null: 'setRefreshController'

### ISSUE THREAD

**Issue by jrheisler** [MayLau-CbL/flutter_horizontal_data_table#21]
I just upgraded from 1.0.9 to 2.0 and get this whenever I close a horizontal data table:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown while finalizing the widget tree:
NoSuchMethodError: invalid member on null: 'setRefreshController'

When the exception was thrown, this was the stack: 
packages/horizontal_data_table/horizontal_data_table.dart 191:33                                                 dispose
packages/flutter/src/widgets/framework.dart 4901:11                                                              unmount
packages/flutter/src/widgets/framework.dart 2026:12                                                              [_unmount]
packages/flutter/src/widgets/framework.dart 2024:7                                                               <fn>
packages/flutter/src/widgets/framework.dart 6151:23                                                              visitChildren
...

**Comment by MayLau-CbL** [comment]
Thank you for the report! I have uploaded a new version 2.0.1 to pub.dev. Feel free to let me know if there is any other problems.
