### ISSUE TITLE
HorizontalDataTable height based on number of rows

### ISSUE THREAD

**Issue by SachinTanpure** [MayLau-CbL/flutter_horizontal_data_table#27]
How to make horizontalDataTable height adjust to number of rows? Right now height is matched to parent widget even though table has one row

**Comment by MayLau-CbL** [comment]
since the scrollview and the positioned widget cannot accept a non specified height, directly using shrinkWrap on those listview seems not work. I will think of another solution later. But I think I can expose a tableHeight param that allow manually adjust the height of the table for now.
