### ISSUE TITLE
[Question] is it possible to fix the first two column

### ISSUE THREAD

**Issue by yang6626** [MayLau-CbL/flutter_horizontal_data_table#30]
hi there
thanks for your effort.
i has try to return Row in leftSideItemBuilder to make two column fixed, but there is something wrong with the header. the first item from the headerWidgets go to the left side as expected, but the second item goes to the right side even when the width of leftHandSideColumnWidth is big enough to put two column in. is there an other way to do that? sorry for the lousy english, hope you can understand what i am trying to say. thanks.
![image](https://user-images.githubusercontent.com/63634780/108590247-5f3fab80-739d-11eb-9e14-284740355d7a.png)

**Comment by MayLau-CbL** [comment]
I understand what you mean. This is because the headerWidgets param will take the index [0] as the left hand-side header widget. I will think about how to update this part for more flexibility on setting what should be the left and what should be the right hand-side widget.

For now a quick solution for this:
```
List<Widget> _getTitleWidget() {
    return [
      //Use a row widget to hold the 1st column header and 2nd column header
      Row(
        children: [
          FlatButton(
            padding: EdgeInsets.all(0),
            child: _getTitleItemWidget(
                'Name' +
                    (sortType == sortName ? (isAscending ? '↓' : '↑') : ''),
                100),
            onPressed: () {
              sortType = sortName;
              isAscending = !isAscending;
              user.sortName(isAscending);
              setState(() {});
            },
          ),
          FlatButton(
            padding: EdgeInsets.all(0),
            child: _getTitleItemWidget(
                'Status' +
                    (sortType == sortStatus ? (isAscending ? '↓' : '↑') : ''),
                100),
            onPressed: () {
              sortType = sortStatus;
              isAscending = !isAscending;
              user.sortStatus(isAscending);
              setState(() {});
            },
          ),
        ],
      ),
      _getTitleItemWidget('Phone', 200),
      _getTitleItemWidget('Register', 100),
      _getTitleItemWidget('Termination', 200),
    ];
  }
```

**Comment by yang6626** [comment]
haha，，i about to close it. i figure it out to return Row when index is 0 after i posted the issue. thanks for your quick response.
