### ISSUE TITLE
isAlwaysShown was called on null

### ISSUE THREAD

**Issue by Kimhak-Loem** [MayLau-CbL/flutter_horizontal_data_table#36]
Hi
I try to workaround with the example in Readme. And I got error` 'isAlwaysShown' was called on null`. As you can see in below image.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/25259408/109749026-3c26be80-7c1d-11eb-9f7d-fac4eba66620.png">

I use Mac with below version:
- Flutter 1.22.6 • channel stable
- Dart 2.10.5

**Comment by MayLau-CbL** [comment]
yea, you are right, i have missed the default isAlwaysShown after disabled the color part. I will make a quick fix today for fixing this. For now, just temp solution to avoid this error, you can add this 2 configuration to the widget
verticalScrollbarStyle: ScrollbarStyle(),
horizontalScrollbarStyle: ScrollbarStyle(),

**Comment by Kimhak-Loem** [comment]
@MayLau-CbL thank you for your quick response. I have try with what you mention, but the error still occurred.

```
      verticalScrollbarStyle: const ScrollbarStyle(
          isAlwaysShown: true,
          thickness: 4.0,
          radius: Radius.circular(5.0),
        ),
        horizontalScrollbarStyle: const ScrollbarStyle(
          isAlwaysShown: true,
          thickness: 4.0,
          radius: Radius.circular(5.0),
        ),
```

**Comment by MayLau-CbL** [comment]
Weird🤔. I will make a deep check later. And sorry for taking your time on that. Will let you know when it is fixed.

**Comment by Kimhak-Loem** [comment]
@MayLau-CbL thank you. FYI, my friend also didn't run into this issue. I'm also confused.
