### ISSUE TITLE
right-to-left (RTL) ?

### ISSUE THREAD

**Issue by morteza2m** [MayLau-CbL/flutter_horizontal_data_table#4]
Hi,
I wanted to create an Arabic (right-to-left) app.
how to show right-to-left (RTL) data-table in Flutter?

**Comment by MayLau-CbL** [comment]
@morteza2m Do you mean the fixed column on the right and the scrollable columns on the left?

**Comment by Ahmedmedhat187** [comment]
Hi,

I want to make footer to the table
https://drive.google.com/file/d/1isoaBXQu_-NErPfsgF6sLM5LyVotoFcO/view[table footer]

**Comment by MayLau-CbL** [comment]
@Ahmedmedhat187 do you mean a fixed footer at the bottom?

**Comment by mahmoud-haj-ali** [comment]
> @morteza2m Do you mean the fixed column on the right and the scrollable columns on the left?

Yes, that is what he is mean.
Can you support this feature?
