### ISSUE TITLE
'RawScrollbar' isn't defined for the class 'CustomScrollBar'

### ISSUE THREAD

**Issue by demo-Ashif** [MayLau-CbL/flutter_horizontal_data_table#40]
Applied the library but I couldn't run the project due to this error. 

`Error: The method 'RawScrollbar' isn't defined for the class 'CustomScrollBar'.
 - 'CustomScrollBar' is from 'package:horizontal_data_table/scroll/custom_scroll_bar.dart' ('/C:/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-2.5.2/lib/scroll/custom_scroll_bar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'RawScrollbar'.
      return RawScrollbar(
             ^^^^^^^^^^^^
`
Need solution to go forward. Using version 2..5.2

**Comment by MayLau-CbL** [comment]
Hi @demo-Ashif , just notice the v2.5.2 should use alone with the latest flutter version (>1.22.6) as the RawScrollbar is only supported recently.🤦‍♀️ I understand this is a bit confusing, but please use the version that fit your situation for now until the null-safety migration is done.
 
If not using the latest version, please use v2.5.1
The null-safety is still working in progress. 
If using latest flutter version without sound null safety, please use v2.5.2.
If using latest flutter version with sound null safety, please wait for the next version.

**Comment by demo-Ashif** [comment]
> Hi @demo-Ashif , just notice the v2.5.2 should use along with the latest flutter version (>1.22.6) as the RawScrollbar is only supported recently.🤦‍♀️ I understand this is a bit confusing, but please use the version that fit your situation for now until the null-safety migration is done.
> 
> If not using the latest version, please use v2.5.1
> The null-safety is still working in progress.
> If using latest flutter version without sound null safety, please use v2.5.2.
> If using latest flutter version with sound null safety, please wait for the next version.

Facing very weird issue. Used 2.5.1 as per your advice as am using flutter version 1.22.5 but still its giving same error. I deleted whole .pub-cache folder and get packages again. But still giving exactly same error. Really can't understand.

**Comment by demo-Ashif** [comment]
> Hi @demo-Ashif , just notice the v2.5.2 should use along with the latest flutter version (>1.22.6) as the RawScrollbar is only supported recently.🤦‍♀️ I understand this is a bit confusing, but please use the version that fit your situation for now until the null-safety migration is done.
> 
> If not using the latest version, please use v2.5.1
> The null-safety is still working in progress.
> If using latest flutter version without sound null safety, please use v2.5.2.
> If using latest flutter version with sound null safety, please wait for the next version.

Thanks for updating
