### ISSUE TITLE
[Question]Save and restore scroll position.

### ISSUE THREAD

**Issue by nrikiji** [MayLau-CbL/flutter_horizontal_data_table#42]
Can you tell me if there is a way to implement saving and restoring the scroll position?

**Comment by MayLau-CbL** [comment]
I suggest init a ScrollController for the verticalScrollController. And then you can get and set the scroll information to that controller outside the HorizontalDataTable widget.

```
ScrollController _scrollController = ScrollController();
HorizontalDataTable(
    ...
    verticalScrollController: _scrollController,
)
```

**Comment by nrikiji** [comment]
Thank you very much.
