### ISSUE TITLE
Executable example project request

### ISSUE THREAD

**Issue by singnoi** [MayLau-CbL/flutter_horizontal_data_table#5]
I have download the project but it was not runnable,

can you upload runnable example to speed up the learning curve of new dev,

thanks so much

**Comment by MayLau-CbL** [comment]
Sure, I can update it in next round.
Or you may start a new project just and copy the example/main.dart to it.🙂


在 2020年2月12日週三 14:53，singnoi <notifications@github.com> 寫道：

**Comment by singnoi** [comment]
Thank you for your response.
sorry I don't know how to install this widget in pubspec.yaml there is no guide in web

this picture is what i'm stuck, thank you

<img width="610" alt="main_dart_—_table3" src="https://user-images.githubusercontent.com/59789789/74311364-e11bf280-4da1-11ea-8cd9-3b3c53fef721.png">

**Comment by MayLau-CbL** [comment]
No worries, just feel free to ask. 

You can install it like the following in the pubspec,yaml, please note that there is 2 'space' before the horizontal_data_table.

dependencies:
  flutter:
    sdk: flutter
  horizontal_data_table: ^1.0.5

Detail can ref to: https://pub.dev/packages/horizontal_data_table#-installing-tab-

**Comment by MayLau-CbL** [comment]
Updated new executable example project
