### ISSUE TITLE
[Question]Set "BouncingScrollPhysics" to "scrollPhysics".

### ISSUE THREAD

**Issue by Yuki-Ut** [MayLau-CbL/flutter_horizontal_data_table#54]
**Describe the Problem**
Please tell me about the setting of "scrollPhysics".
"BouncingScrollPhysics" is set in "scrollPhysics".
However, when scrolling the line, the positions of "leftSideItemBuilder" and "rightSideItemBuilder" are misaligned.
"RightSideItemBuilder" returns to its initial position while scrolling "leftSideItemBuilder".
Is there a way to link "leftSideItemBuilder" and "rightSideItemBuilder"?

[1.Initial position]
<img width="381" alt="No01" src="https://user-images.githubusercontent.com/86274560/122855508-4e557580-d350-11eb-9b63-9e3c823bc0ba.png">

[2.Scrolling]
<img width="379" alt="No02" src="https://user-images.githubusercontent.com/86274560/122855528-544b5680-d350-11eb-9dba-6963ab172b7a.png">

[3.Stop scrolling]
<img width="380" alt="No03" src="https://user-images.githubusercontent.com/86274560/122855537-59100a80-d350-11eb-9bbf-54048c2a727a.png">

**Comment by MayLau-CbL** [comment]
Would you mind showing ur horizontal table widget config set up or if possible a small example project?

**Comment by Yuki-Ut** [comment]
I have created a zip file for my project.
I edited and created the sample code of "pub.dev".
"scrollPhysics" is set on line 90 of "main.dart".

**Comment by Yuki-Ut** [comment]
I have created a zip file for my project.
I edited and created the sample code of "pub.dev".
"scrollPhysics" is set on line 90 of "main.dart".
[table_test_application.zip](https://github.com/MayLau-CbL/flutter_horizontal_data_table/files/6692953/table_test_application.zip)

**Comment by MayLau-CbL** [comment]
i understand your problem, when you pulling to scroll and holding for a few second, the left and right is not sync to the same position which is a known issue. this is hard to solve at the moment, at least still not have a good idea on this for each types of physics, let me explain the problem. This horizontal table is based on 2 listview and synchronise each other by listening each scroll notification. The notification itself will not notify every offset moved that cause the motion not that sync. And the bounce physics  extend drawn will not reflect on the offset returned after holding for a few second but on its physics extends viewport, that is why you see the left side is on the top.

**Comment by MayLau-CbL** [comment]
no further comment, close this first
