### ISSUE TITLE
[Bug][Web] Horizontal scrollbar disappears even when `isAlwaysShown: true`

### ISSUE THREAD

**Issue by wreppun** [MayLau-CbL/flutter_horizontal_data_table#59]
**Describe the bug**
Horizontal scrollbar disappears when scrolling vertically, even with `isAlwaysShown` set to true. 

**Platform**
Web, run with `flutter run -d chrome`.  

**Screen Captures or Debug Log**

First screenshot shows horizontal and vertical scrollbars visible on initial render
<img width="734" alt="Screen Shot 2021-09-24 at 8 21 36 PM" src="https://user-images.githubusercontent.com/1791503/134761207-f0767f77-f2c6-4182-add2-7948d35ed2c4.png">

Second screenshot shows missing horizontal scrollbar after starting to scroll vertically. 
<img width="734" alt="Screen Shot 2021-09-24 at 8 21 56 PM" src="https://user-images.githubusercontent.com/1791503/134761282-3ae72ea5-7a6e-4b36-a6f9-acfe28a0a3e2.png">

**Additional context**

This is fairly important for web users, who may be using a physical mouse and thus need to drag the scrollbar to scroll horizontally.

I think I have a fix locally and I'll create a PR.

**Comment by MayLau-CbL** [comment]
Thanks for the help! Do you mind also telling me the flutter version to simulate this? I will play around the pr later.😀

**Comment by wreppun** [comment]
No problem!  This happens on stable (`2.5.0`).
