### ISSUE TITLE
加上onload函数

### ISSUE THREAD

**Issue by Shadow404** [MayLau-CbL/flutter_horizontal_data_table#68]
没有下拉，没法刷新数据啊宝

**Comment by MayLau-CbL** [comment]
repeated #62
i am still oning it, welcome to help contribution 😉

**Comment by Shadow404** [comment]
thanks&nbsp;for you did it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "May ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 中午1:53
收件人: ***@***.***&gt;; 
抄送: "🇶 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MayLau-CbL/flutter_horizontal_data_table] 加上onload函数 (Issue #68)





 
repeated #62
 i am still oning it, welcome to help contribution 😉
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
