### ISSUE TITLE
Image disappears

### ISSUE THREAD

**Issue by KarolNiemiec** [MayLau-CbL/flutter_horizontal_data_table#69]
Hello,
when use horizontal scrolling my image.memory(base64String) dissappears, any solution ?

**Comment by MayLau-CbL** [comment]
can you please provide a simple project to simulate your question? Thanks!

**Comment by KarolNiemiec** [comment]
@MayLau-CbL 
try this one
https://github.com/KarolNiemiec/test

**Comment by MayLau-CbL** [comment]
confirmed issue is solved after v4.0.0
and a new example is added with #99
