### ISSUE TITLE
外层高度必须设置？

### ISSUE THREAD

**Issue by zhouxting** [MayLau-CbL/flutter_horizontal_data_table#7]
必须在外层包裹一个有高度的容器？

**Comment by MayLau-CbL** [comment]
如果整頁都是horizontal data table widget的話，其實是可以不加有高度的container的，因為會默認為填滿整個空間。
但是若作為子系的widget下，就必須加上有高度的container或是使用expanded之類，讓整個表格可以有一個限制的高度，繼而才能讓表格內裡的scrollable 正常運作。
