### ISSUE TITLE
ExtraPadding before Header[Bug]

### ISSUE THREAD

**Issue by dlondonog** [MayLau-CbL/flutter_horizontal_data_table#70]
**Describe the bug**
I am using `horizontal_data_table: ^ 3.5.0`. I am quite confused because I have not get to remove an Extra Padding that is putting the Widget just before displaying the Header (see Graph 1). A proof that this extra padding is specifically due to `Horizontal_Data_Table`, is that if I change this function to a simple text that says 'Hello' that padding stops appearing. How can I remove this padding?

[ExtraPadding - Graph 1](https://user-images.githubusercontent.com/71848788/143506397-cc7b0bca-b257-4f75-bcac-973eee023c7e.jpg)

The code I am using in Horizontal Data Table is as follows:

    StreamBuilder(
            stream: estanquesBloc.estanqueLoteStream,
            builder: (BuildContext context, AsyncSnapshot<List<LoteModel>> snapshot){
              if (snapshot.hasData) {
                loteList = snapshot.data;
                if (loteList!.isEmpty) return _imagenInicial(context);
                return HorizontalDataTable(
                  leftHandSideColumnWidth: _size.width*(0.13+0.045), 
                  rightHandSideColumnWidth: _size.width*(0.1*7+0.15),
                  isFixedHeader: true,
                  headerWidgets: _titulos(),
                  leftSideItemBuilder: (context, i) =>_crearItemsPrimeraColumna(context, loteList![i]),
                  rightSideItemBuilder: (context, i) =>_crearItemsSiguientesColumnas(context, loteList![i]),
                  itemCount: loteList!.length,
                  rowSeparatorWidget: Container(
                    height: 10.0,
                    color: Colors.grey[200],
                  ),
                  htdRefreshController: _hdtRefreshController,
                );
              } else if (snapshot.hasError) {
                return Text(snapshot.error.toString());
              } 
                return const Center (child: Image(image: AssetImage('assets/Aplians-fish-Preloader.gif'), height: 100.0,));
            }
        );

If I change HorizontalDataTable by a Hello Text the result is as follows:

[No Extra Padding - Graph 2](https://user-images.githubusercontent.com/71848788/143506380-0cc9105c-1d6e-45b1-aa8e-c0da55f94330.jpg)

The code to demonstrate that the Padding is due to HorizontalDataTable Widget is as follows:

    StreamBuilder(
            stream: estanquesBloc.estanqueLoteStream,
            builder: (BuildContext context, AsyncSnapshot<List<LoteModel>> snapshot){
              if (snapshot.hasData) {
                loteList = snapshot.data;
                if (loteList!.isEmpty) return _imagenInicial(context);
                return Text('Hello');
              } else if (snapshot.hasError) {
                return Text(snapshot.error.toString());
              } 
                return const Center (child: Image(image: AssetImage('assets/Aplians-fish-Preloader.gif'), height: 100.0,));
            }
        );

**Platform**
I'm testing on IOS and Android

**Screen Captures or Debug Log**
It was included

**Additional context**
It was included

**Comment by dlondonog** [comment]
I can see that this bug is related with `extendBodyBehindAppBar: true` property on Scaffold. Does HorizontalDataTable is compatible with this property?

**Comment by MayLau-CbL** [comment]
no further comment, close this first

**Comment by fevxie** [comment]
This issue will happen when active SliverAppBar widget  in my scene

**Comment by MayLau-CbL** [comment]
> This issue will happen when active SliverAppBar widget  in my scene

May you help giving more information if possible what combinations or widget will cause this? Thanks 🙏
