### ISSUE TITLE
 "renderflex overflowed-by-infinity-pixels-on-the-bottom" while wrapping horizontal datatable in Column Widget

### ISSUE THREAD

**Issue by Uvais-Mohammad** [MayLau-CbL/flutter_horizontal_data_table#72]
I need to wrap **HorizontalDataTable** within a Column Widget for adding a **TextField** above table. But it is showing "**renderflex** overflowed-by-infinity-pixels-on-the-bottom"

**Comment by MayLau-CbL** [comment]
As the table is based on scrollable (listview), it requires declaring height of the table. you may try wrap a Sizedbox with fixed height or Extended based on the design.

**Comment by Uvais-Mohammad** [comment]
It worked and thank you so much❤❤
