### ISSUE TITLE
The header disappears under certain conditions [Bug]

### ISSUE THREAD

**Issue by R4x03** [MayLau-CbL/flutter_horizontal_data_table#74]
**Describe the bug**
The header disappears when the table is scrollable vertically. However, the moment I scroll down or up it reappears, and as soon as the screen stops moving, it disappears again. The bug seems to trigger in portrait and landscape mode

**Platform**
iPhone and iPad, when Flutter **Web** is launched, and the website is accessed from safari

**Screen Captures or Debug Log**
iPad Po (11-inch) - 3rd generation, iOS 15.2 in landscape mode
<img width="878" alt="Capture d’écran 2022-02-01 à 11 06 19" src="https://user-images.githubusercontent.com/64418839/151949253-3849bdbf-a067-4fbc-8795-2dfc2898d593.png">

iPhone 13 - iOS 15.2 in portrait mode
<img width="418" alt="Capture d’écran 2022-02-01 à 11 14 44" src="https://user-images.githubusercontent.com/64418839/151950436-1a3d6273-d6f3-41e0-a0e3-0a411abc3c60.png">
 
**Additional context**
The problem does not occur on Safari on mac. It happens sometimes that the header works at the beginning, but staying on the board for a few seconds and scrolling, the problem reappears

**Comment by MayLau-CbL** [comment]
I have tried to test with the example project with iphone and ipad's safari and chrome, i cannot reproduce this problem. but for this kinds of issue, i doubt this is related to either (1) the width or height of the header is somehow overflowed when doing some event like scroll in the affected device or (2) text magnification.

for (1) you may try to run a debug one on the simulator or even real device to check if any log is collected
for (2) i am not sure if choosing a canvas renderer or locking the text scaling would be help

**Comment by R4x03** [comment]
Thank you for your help! Finally the problem seems to come from the web renderer. If I choose HTML renderer instead of CanvasKit renderer, there doesn't seem to be a problem anymore
