### ISSUE TITLE
How can I detect end of horizontal scrolling through table [Question]

### ISSUE THREAD

**Issue by mhilalsh** [MayLau-CbL/flutter_horizontal_data_table#75]
I'm trying to change some style in the screen depending on user scrolling the horizontal data table, is there's a way to add an event to the table like "onScroll" or "onScrollEnding" to trigger a function or set the state to refresh the page and update the UI?

**Comment by MayLau-CbL** [comment]
there is a param called verticalScrollController which can assign the scrollController out of the horizontal table widget. you may assign the controller and addListener to it which should then allow you to track the scroll status by the offset.
