### ISSUE TITLE
When asynchronous data takes time to load, the left side of the last piece of data is not displayed[Bug]

### ISSUE THREAD

**Issue by junwinner** [MayLau-CbL/flutter_horizontal_data_table#76]
![image](https://user-images.githubusercontent.com/18690937/153333829-0219132a-16f2-4b35-8450-de2a8e90e5ce.png)
![image](https://user-images.githubusercontent.com/18690937/153334107-0d909055-7741-470f-b7ea-521eadc6148e.png)

**Comment by junwinner** [comment]
upgrading flutter version to  2.10.1 solved the problem

**Comment by MayLau-CbL** [comment]
no further comment, close this first

**Comment by junwinner** [comment]
你好，我是谢高军，你的来信我已收到,谢谢!
