### ISSUE TITLE
可以加上上拉加载更多功能吗？

### ISSUE THREAD

**Issue by kzq5** [MayLau-CbL/flutter_horizontal_data_table#8]
你好，可以加上上拉加载更多功能吗？
毕竟表格的话会有很多数据，如果一次性加载完太消耗性能了。

**Comment by MayLau-CbL** [comment]
現時的原理其實是使用了兩個listview去顯示資料，若果使用了builder去建構cell widget的話，理論上它是lazy build，應該不會出現一次加載太多而導致效能太差的情況，當然是假設widget的高度不是設致得太高或不是dynamic高度的話😅。

不過你提到的功能我也覺得值得加建，因為我都遇到不少內地的app設計是使用上拉或下推再加載更多資料，若你不介意有沒有什麼推薦的sample app 或設計意見可以給我作為參考。謝謝！

**Comment by kzq5** [comment]
我们app中用的是这个第三方pull_to_refresh，支持上拉加载更多以及下拉刷新，我嵌套进去发现不能用，暂时在想办法改你的源码，你也可以参考着改下试试。如果你改好了希望给我留言，谢谢！

**Comment by MayLau-CbL** [comment]
Added new issue for this feature https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/16
