### ISSUE TITLE
in Flutter 3.x.x version, WidgetsBinding.instance.addPostFrameCallback change

### ISSUE THREAD

**Issue by Go-oG** [MayLau-CbL/flutter_horizontal_data_table#83]
in Flutter 3.x.x version

All WidgetsBinding.instance.addPostFrameCallback  method should become  WidgetsBinding.instance?.addPostFrameCallback

tips:nullsafe

**Comment by MayLau-CbL** [comment]
Issue resolved along since 4.1.0, close this issue
if any similar warning pop again, feel free to re-open
