### ISSUE TITLE
[Feature] can't run example on Linux

### ISSUE THREAD

**Issue by guyluz11** [MayLau-CbL/flutter_horizontal_data_table#94]
**Describe the Feature**
I would like to run the example on my Linux computer, but when I try to run I am getting an error message saying that this project does not support Linux and I can add it by following the instructions under [here](https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app).

**Describe the Solution**
Running the command 
`flutter create --platforms=windows,macos,linux .`
As described in the [linked flutter site](https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app).

**Comment by MayLau-CbL** [comment]
Version release along with horizontal_data_table: ^4.1.1
Thanks again for the contribution!
