### ISSUE TITLE
(childView.primary ? PrimaryScrollController.of(context) : null);

### ISSUE THREAD

**Issue by prajwalcognerium** [MayLau-CbL/flutter_horizontal_data_table#98]
**Describe the bug**
Description of what the bug is.

../flutter/.pub-cache/hosted/pub.dartlang.org/horizontal_data_table-4.1.1+1/lib/refresh/pull_to_refresh/src/smart_refresher.dart:412:24: Error: A value of type 'bool?' can't be assigned to a variable
of type 'bool' because 'bool?' is nullable and 'bool' isn't.
            (childView.primary ? PrimaryScrollController.of(context) : null);

Flutter 3.1.0-0.0.pre.1376 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3598f20002 (9 days ago) • 2022-06-26 18:19:04 -0400
Engine • revision ee56813c14
Tools • Dart 2.18.0 (build 2.18.0-228.0.dev) • DevTools 2.14.1

**Platform**
Please describe the affected platfrom(eg. IOS, Android, Web, Window, Mac, Linux)

**Screen Captures or Debug Log**
If applicable, add screenshots or debug log to help explain your problem.
 
**Additional context**

**Comment by thahaniayoob** [comment]
I'm using this package on an app which is currently being used. Because of this bug, I haven't been able to release a new version of it. Please debug this ASAP. If possible kindly inform by when it will be fixed. Thank You.

**Comment by MayLau-CbL** [comment]
I have published a pre-release version for this https://pub.dev/packages/horizontal_data_table/versions/4.1.2-debug based on the branch [fix/incorrect-type-for-master-3.1.0-0.0.pre.1376](https://github.com/MayLau-CbL/flutter_horizontal_data_table/tree/fix/incorrect-type-for-master-3.1.0-0.0.pre.1376)
Stable version will alive if this go to stable channel.

**Comment by likYim** [comment]
Hello, I am in stable Flutter 3.3.0 and cannot run app with this error. Please merge the update to release version. Thanks a lot.

**Comment by MayLau-CbL** [comment]
released in new package with v4.1.2
